// Competitor data for /vs/[competitor] and /alternative/[competitor] pages

export const COMPETITORS = {
  apollo: {
    slug: 'apollo',
    name: 'Apollo.io',
    domain: 'apollo.io',
    tagline: 'La base de données B2B mondiale',
    description: 'Apollo.io est une plateforme de prospection B2B avec une base de 220M+ contacts. Très utilisée aux USA, elle est moins performante sur les PME et marchés locaux français.',
    pricing: 99,
    pricingUnit: '$/mois',
    strengths: [
      'Énorme base de contacts mondiale (220M+)',
      'Intégrations Salesforce, HubSpot natives',
      'Séquences d\'outreach intégrées',
    ],
    weaknesses: [
      'Très cher (99$/mo pour le plan Basic, ~150$ avec emails illimités)',
      'Mauvaise couverture des PME françaises et commerces locaux',
      'Données souvent obsolètes pour la France (>2 ans)',
      'Interface en anglais uniquement',
      'Pas de Google Places intégré (manque les commerces locaux)',
    ],
    bestFor: 'Grandes entreprises B2B SaaS vendant aux USA',
    color: 'orange',
  },
  hunter: {
    slug: 'hunter',
    name: 'Hunter.io',
    domain: 'hunter.io',
    tagline: 'Trouvez les emails par domaine',
    description: 'Hunter.io est un email finder qui devine les emails à partir d\'un nom et d\'un domaine. Bon outil mais limité quand l\'entreprise n\'a pas de site web ou qu\'on cherche sans nom précis.',
    pricing: 49,
    pricingUnit: '$/mois',
    strengths: [
      'Très simple à utiliser',
      'Bonne précision sur les patterns d\'emails',
      'Extension Chrome pratique',
    ],
    weaknesses: [
      'Nécessite obligatoirement un domaine pour fonctionner',
      'Inefficace pour les PME sans site web (~40% des entreprises FR)',
      'Pas de scraping de site, juste pattern matching',
      'Crédits limités (25/mois en gratuit, 500 pour 49$)',
      'Pas de Google Places (pas de recherche par catégorie/zone)',
    ],
    bestFor: 'Recherche ciblée d\'un email précis chez une entreprise connue',
    color: 'amber',
  },
  lusha: {
    slug: 'lusha',
    name: 'Lusha',
    domain: 'lusha.com',
    tagline: 'Données décideurs premium',
    description: 'Lusha est spécialisé dans les données de décideurs B2B (téléphones directs, emails personnels). Cher, focalisé sur le marché US/UK, peu pertinent pour la France.',
    pricing: 36,
    pricingUnit: '$/mois (5 crédits)',
    strengths: [
      'Données de qualité sur les décideurs C-level',
      'Téléphones directs souvent disponibles',
      'Extension LinkedIn pratique',
    ],
    weaknesses: [
      'Très cher au crédit (~7$ par contact en plan Basic)',
      'Pas de recherche en masse (1 contact à la fois)',
      'Couverture France faible (vs USA/UK)',
      'Modèle de prix opaque et imprévisible',
      'Pas d\'export CSV en masse sans plan Enterprise',
    ],
    bestFor: 'Sales enterprise ciblant des décideurs C-level individuels',
    color: 'blue',
  },
  snov: {
    slug: 'snov',
    name: 'Snov.io',
    domain: 'snov.io',
    tagline: 'Email finder + outreach combinés',
    description: 'Snov.io combine email finder et outils d\'outreach (campagnes, drip emails). Solution complète mais avec des crédits limités et une couverture France moyenne.',
    pricing: 39,
    pricingUnit: '$/mois',
    strengths: [
      'Tout-en-un (find + verify + outreach)',
      'Plan gratuit décent (50 crédits/mois)',
      'CRM intégré basique',
    ],
    weaknesses: [
      'Crédits qui s\'épuisent vite (1 email = 1 crédit, 1 vérif = 1 crédit)',
      'Couverture France basée sur LinkedIn uniquement',
      'Pas de Google Places ou recherche locale',
      'Limite de 30 emails/jour en outreach (anti-spam)',
      'Interface complexe pour débuter',
    ],
    bestFor: 'Solo entrepreneur faisant 100-500 emails/mois en outreach',
    color: 'cyan',
  },
  lemlist: {
    slug: 'lemlist',
    name: 'Lemlist',
    domain: 'lemlist.com',
    tagline: 'Cadenceur multicanal avec warmup intégré',
    description: 'Lemlist est un cadenceur multicanal (email + LinkedIn) français premium, populaire pour ses fonctionnalités de personnalisation à l\'échelle et son warmup IP intégré. Idéal pour l\'outreach mais ne fait pas de découverte de prospects.',
    pricing: 59,
    pricingUnit: '€/mois',
    strengths: [
      'Warmup IP natif (Lemwarm)',
      'Personnalisation avancée (images dynamiques, variables IA)',
      'Multi-canal email + LinkedIn natif',
      'Équipe française, support FR',
    ],
    weaknesses: [
      'Pas de découverte de prospects (il faut déjà avoir sa liste)',
      'Pas d\'enrichissement email (à compléter avec Hunter/Dropcontact)',
      'Prix qui monte vite (59 € puis 99 € puis 159 €)',
      'Courbe d\'apprentissage modérée',
    ],
    bestFor: 'Équipes sales 2-10 personnes voulant un cadenceur premium avec warmup',
    color: 'pink',
  },
  dropcontact: {
    slug: 'dropcontact',
    name: 'Dropcontact',
    domain: 'dropcontact.com',
    tagline: 'Enrichissement email RGPD-by-design français',
    description: 'Dropcontact est un service d\'enrichissement email français, conçu RGPD-by-design (filtre des emails personnels, retraitement légal). Excellente couverture France mais ne fait pas de découverte.',
    pricing: 31,
    pricingUnit: '€/mois',
    strengths: [
      'RGPD-by-design natif (le plus strict du marché)',
      'Excellente couverture France',
      'Intégrations Pipedrive, HubSpot, Salesforce natives',
      'Vérification email incluse (pas de bounce)',
    ],
    weaknesses: [
      'Pas de découverte de prospects',
      'Pas de cadenceur intégré',
      'Crédits limités (200 emails/mois en plan starter)',
      'Pas d\'app web : exclusivement via API ou intégrations CRM',
    ],
    bestFor: 'PME françaises voulant enrichir une liste existante avec conformité RGPD stricte',
    color: 'green',
  },
  kaspr: {
    slug: 'kaspr',
    name: 'Kaspr',
    domain: 'kaspr.io',
    tagline: 'Extraction de contacts LinkedIn (email + téléphone)',
    description: 'Kaspr est une extension Chrome qui extrait les contacts (email + téléphone direct) directement depuis LinkedIn et Sales Navigator. Équipe française, focus PME/mid-market européen.',
    pricing: 49,
    pricingUnit: '€/mois',
    strengths: [
      'Téléphones directs souvent disponibles',
      'Extension Chrome très intuitive',
      'Bonne couverture France et Europe',
      'Plan gratuit (5 crédits/jour)',
    ],
    weaknesses: [
      'Dépendant de LinkedIn (quotas + risque de blocage de compte)',
      'Pas de découverte par catégorie ou département',
      'Pas de cadenceur intégré (à compléter avec Lemlist/Smartlead)',
      'Crédits téléphone consommés vite',
    ],
    bestFor: 'BDR/SDR sourçant via LinkedIn Sales Navigator',
    color: 'indigo',
  },
  cognism: {
    slug: 'cognism',
    name: 'Cognism',
    domain: 'cognism.com',
    tagline: 'Sales intelligence enterprise focus EU',
    description: 'Cognism est une plateforme de sales intelligence enterprise focalisée sur le marché européen. Base de données massive avec téléphones directs vérifiés, conformité RGPD native. Très chère.',
    pricing: 1500,
    pricingUnit: '€/mois (annuel)',
    strengths: [
      'Base mid-market et enterprise EU très complète',
      'Téléphones directs vérifiés ("Diamond Verified")',
      'Conformité RGPD native (Don\'t Not Call lists EU)',
      'Intent data inclus',
    ],
    weaknesses: [
      'Cher (1500 €/mois minimum, contrat annuel)',
      'Pas adapté aux TPE/PME (overkill)',
      'Couverture France correcte mais centrée mid/enterprise',
      'Onboarding long, peu de self-service',
    ],
    bestFor: 'Scale-ups et grands comptes ciblant le mid-market et l\'enterprise EU',
    color: 'purple',
  },
  zoominfo: {
    slug: 'zoominfo',
    name: 'ZoomInfo',
    domain: 'zoominfo.com',
    tagline: 'Leader US de la sales intelligence',
    description: 'ZoomInfo est le leader américain de la sales intelligence avec une base de 150M+ professionnels. Couverture France correcte mais ressources sous-utilisées pour le marché français.',
    pricing: 1200,
    pricingUnit: '€/mois (annuel)',
    strengths: [
      'Base US massive (150M+ contacts)',
      'Intent data + technographic data',
      'Intégrations natives Salesforce, HubSpot, Outreach',
      'Workflows et automation puissants',
    ],
    weaknesses: [
      'Très cher (1200 €/mois minimum, engagement annuel)',
      'Couverture France moyenne (centré US)',
      'Données souvent obsolètes en Europe',
      'Pas de self-service, onboarding obligatoire',
    ],
    bestFor: 'Entreprises B2B SaaS US/internationales avec budget',
    color: 'sky',
  },
  findymail: {
    slug: 'findymail',
    name: 'Findymail',
    domain: 'findymail.com',
    tagline: 'Email finder avec vérification SMTP intégrée',
    description: 'Findymail est un email finder spécialisé dans la vérification SMTP avancée, avec un fort taux de précision (95%+ valid emails). Bon complément à un outil de découverte.',
    pricing: 49,
    pricingUnit: '$/mois',
    strengths: [
      'Vérification SMTP très fiable (~95% valid emails)',
      'Intégrations Salesforce, HubSpot, Pipedrive',
      'API simple et bien documentée',
      'Pricing transparent au crédit',
    ],
    weaknesses: [
      'Pas de découverte de prospects',
      'Pas de cadenceur intégré',
      'Crédits qui s\'épuisent vite (1000 emails = 49 $)',
      'Centré sur les emails US/internationaux',
    ],
    bestFor: 'Vérification d\'emails avant outreach pour éviter les bounces',
    color: 'emerald',
  },
  smartlead: {
    slug: 'smartlead',
    name: 'Smartlead',
    domain: 'smartlead.ai',
    tagline: 'Cadenceur cold email avec délivrabilité optimisée',
    description: 'Smartlead est un cadenceur cold email orienté délivrabilité maximale : warmup IP avancé, multi-inbox rotation, AI-powered. Très populaire dans la communauté outbound 2025-2026.',
    pricing: 29,
    pricingUnit: '$/mois',
    strengths: [
      'Délivrabilité parmi les meilleures du marché',
      'Multi-inbox rotation (envoie depuis plusieurs adresses pour éviter spam)',
      'Warmup IP inclus illimité',
      'Prix d\'entrée très accessible (29 $)',
    ],
    weaknesses: [
      'Pas de découverte de prospects',
      'Pas d\'enrichissement email',
      'Interface en anglais uniquement',
      'Support communautaire (pas FR)',
    ],
    bestFor: 'Solo entrepreneurs et agences voulant un cadenceur efficace à bas coût',
    color: 'rose',
  },
  instantly: {
    slug: 'instantly',
    name: 'Instantly',
    domain: 'instantly.ai',
    tagline: 'Cadenceur scale avec warmup IP unlimited',
    description: 'Instantly est un cadenceur cold email US orienté volume, avec warmup IP illimité et rotation d\'inboxes. Populaire chez les agences outbound américaines.',
    pricing: 37,
    pricingUnit: '$/mois',
    strengths: [
      'Warmup IP illimité',
      'Rotation d\'inboxes natif',
      'Scale jusqu\'à plusieurs millions d\'emails/mois',
      'Marketplace de leads intégré',
    ],
    weaknesses: [
      'Pas de découverte ciblée par secteur/département',
      'Centré sur le marché US',
      'Interface dense, courbe d\'apprentissage',
      'Pas de support français',
    ],
    bestFor: 'Agences outbound et entreprises B2B faisant du volume international',
    color: 'amber',
  },
  waalaxy: {
    slug: 'waalaxy',
    name: 'Waalaxy',
    domain: 'waalaxy.com',
    tagline: 'Automatisation LinkedIn + email français',
    description: 'Waalaxy est une extension Chrome française pour automatiser la prospection LinkedIn (visites, invitations, messages) avec relais email. Très populaire chez les freelances et TPE FR.',
    pricing: 56,
    pricingUnit: '€/mois',
    strengths: [
      'Très simple à prendre en main',
      'Équipe française, support FR',
      'Templates de séquences pré-faits',
      'Intégration Hubspot, Salesforce, Pipedrive',
    ],
    weaknesses: [
      'Centré LinkedIn (peu de prospection email pure)',
      'Risque de blocage de compte LinkedIn si quotas non respectés',
      'Pas de découverte d\'entreprises hors LinkedIn',
      'Pas adapté aux marchés B2B sans présence LinkedIn (artisans, restaurants)',
    ],
    bestFor: 'Freelances et TPE faisant de la prospection LinkedIn-first',
    color: 'violet',
  },
  'la-growth-machine': {
    slug: 'la-growth-machine',
    name: 'La Growth Machine',
    domain: 'lagrowthmachine.com',
    tagline: 'Plateforme multicanal email + LinkedIn + Twitter',
    description: 'La Growth Machine (LGM) est une plateforme française de prospection multicanale (email + LinkedIn + Twitter) avec un focus sur la personnalisation à l\'échelle. Populaire en France et Europe.',
    pricing: 90,
    pricingUnit: '€/mois',
    strengths: [
      'Multicanal natif (email + LinkedIn + Twitter)',
      'Personnalisation IA avancée',
      'Équipe française, support FR',
      'Intégrations CRM natives',
    ],
    weaknesses: [
      'Pas de découverte de prospects',
      'Pas d\'enrichissement email natif',
      'Prix élevé pour démarrer (90 € minimum)',
      'Courbe d\'apprentissage modérée',
    ],
    bestFor: 'Équipes sales 3-15 personnes voulant une plateforme multicanale française',
    color: 'fuchsia',
  },
};

export function getCompetitor(slug) {
  return COMPETITORS[slug] || null;
}

export function getAllCompetitors() {
  return Object.values(COMPETITORS);
}
